Repository 5MYBAB/itta-bab-frontend, pull requests merged in 2024-10, with the labels that each got.

#1 docs: pr 템플릿 추가
  .github/pull_request_template.md
Labels: docs

#3 style: css 기본 설정
  itta-bab-frontend/public/index.html
  itta-bab-frontend/src/App.vue
  itta-bab-frontend/src/components/common/Header.vue
  itta-bab-frontend/src/main.js
  itta-bab-frontend/src/resetcss.css
Labels: style

#5 feat: longin page 기본 완료
  itta-bab-frontend/src/asset/login-logo.png
  itta-bab-frontend/src/asset/resetcss.css
  itta-bab-frontend/src/components/common/Header.vue
  itta-bab-frontend/src/main.js
  itta-bab-frontend/src/views/user/Login.vue
Labels: feat

#7 feat: Footer 구현
  itta-bab-frontend/package-lock.json
  itta-bab-frontend/package.json
  itta-bab-frontend/src/App.vue
  itta-bab-frontend/src/assets/css/resetcss.css
  itta-bab-frontend/src/assets/icons/kakaotalk.svg
  itta-bab-frontend/src/assets/icons/login-logo.png
  itta-bab-frontend/src/components/common/Footer.vue
  itta-bab-frontend/src/components/common/Header.vue
  itta-bab-frontend/src/main.js
  itta-bab-frontend/src/views/user/Login.vue
Labels: feat

#9 feat: 비밀번호 찾기 구현
  itta-bab-frontend/src/views/user/FindPassword.vue
Labels: feat

#11 feat: 모임 상세 정보 UI 구현
  itta-bab-frontend/src/assets/icons/itta-bab_logo.svg
  itta-bab-frontend/src/main.js
  itta-bab-frontend/src/views/group/GroupChat.vue
  itta-bab-frontend/src/views/group/GroupDetail.vue
Labels: feat

#14 feat: signup 구현
  itta-bab-frontend/src/App.vue
  itta-bab-frontend/src/assets/css/resetcss.css
  itta-bab-frontend/src/assets/icons/login-logo.png
  itta-bab-frontend/src/assets/icons/login-logo.svg
  itta-bab-frontend/src/assets/icons/logo.svg
  itta-bab-frontend/src/views/user/Login.vue
  itta-bab-frontend/src/views/user/SignUp.vue
  itta-bab-frontend/src/views/user/styles/SignUp.css
Labels: feat

#12 feat: board 게시판 구현
  itta-bab-frontend/src/App.vue
  itta-bab-frontend/src/assets/icons/itta-bab-logo.svg
  itta-bab-frontend/src/views/board/PostDetail.vue
  itta-bab-frontend/src/views/board/PostWrite.vue
Labels: feat

#16 refactor: 로그인 리팩토링
  itta-bab-frontend/src/components/user/LoginForm.vue
  itta-bab-frontend/src/views/user/Login.vue
Labels: refactor

#20 refactor: 비밀번호 찾기 리팩토링
  itta-bab-frontend/src/components/user/FindPasswordForm.vue
  itta-bab-frontend/src/views/user/FindPassword.vue
Labels: refactor

#27 feat: 아이디 찾기 구현
  itta-bab-frontend/src/components/user/FindIdForm.vue
  itta-bab-frontend/src/views/user/FindId.vue
Labels: feat

#25 feat: board 및 common components 쪼개기
  itta-bab-frontend/src/App.vue
  itta-bab-frontend/src/components/common/List.vue
  itta-bab-frontend/src/components/common/PageNumAndWritingButton.vue
  itta-bab-frontend/src/components/common/SearchBarAndSort.vue
  itta-bab-frontend/src/views/board/PostDetail.vue
Labels: feat

#30 feat: 결과창 구현
  itta-bab-frontend/src/components/user/ResultDetail.vue
  itta-bab-frontend/src/views/user/Result.vue
Labels: feat

#29 store regist 구현
  itta-bab-frontend/src/views/store/StoreRegist.vue
Labels: feat

#33 feat: PostCreate,ReportCreate 글 작성 부분 배경색 수정
  itta-bab-frontend/src/views/board/PostComment.vue
  itta-bab-frontend/src/views/board/PostCreate.vue
  itta-bab-frontend/src/views/report/ReportCreate.vue
Labels: feat

#37 feat: 모임 리스트 UI 개발
  itta-bab-frontend/src/views/group/GroupList.vue
Labels: feat

#41 feat: 라우터 구현
  itta-bab-frontend/package-lock.json
  itta-bab-frontend/package.json
  itta-bab-frontend/src/App.vue
  itta-bab-frontend/src/main.js
  itta-bab-frontend/src/router/board.js
  itta-bab-frontend/src/router/group.js
  itta-bab-frontend/src/router/index.js
  itta-bab-frontend/src/router/schedule.js
  itta-bab-frontend/src/router/store.js
  itta-bab-frontend/src/router/user.js
  itta-bab-frontend/src/views/Home.vue
Labels: feat

#42 fix: 라우터 경로 수정
  itta-bab-frontend/src/App.vue
  itta-bab-frontend/src/router/board.js
Labels: fix

#45 feat: store&review create, update 페이지 구현
  itta-bab-frontend/src/components/store/ReviewForm.vue
  itta-bab-frontend/src/components/store/StoreForm.vue
  itta-bab-frontend/src/views/store/MenuCreate.vue
  itta-bab-frontend/src/views/store/ReviewCreate.vue
  itta-bab-frontend/src/views/store/ReviewUpdate.vue
  itta-bab-frontend/src/views/store/StoreCreate.vue
  itta-bab-frontend/src/views/store/StoreUpdate.vue
Labels: feat

#47 fix: storeRegist -> storeCreate로 파일명 수정, 에러 fix
  itta-bab-frontend/src/router/store.js
  itta-bab-frontend/src/views/store/StoreDetail.vue
Labels: fix

#46 feat: Inquiry List 페이지 구현
  itta-bab-frontend/src/views/inquiry/InquiryList.vue
Labels: feat

#50 feat: 모임 등록 UI 개발
  itta-bab-frontend/src/router/group.js
  itta-bab-frontend/src/views/group/GroupRegister.vue
Labels: feat

#52 feat: inquiry route 연결
  itta-bab-frontend/src/router/board.js
  itta-bab-frontend/src/router/index.js
  itta-bab-frontend/src/router/inquiry.js
  itta-bab-frontend/src/views/inquiry/Inquiry.vue
  itta-bab-frontend/src/views/inquiry/InquiryList.vue
Labels: feat

#57 feat: report list 구현
  itta-bab-frontend/src/router/report.js
  itta-bab-frontend/src/views/report/ReportList.vue
Labels: feat

#59 Feature/group/#51
  itta-bab-frontend/src/components/common/BottomPageButton.vue
  itta-bab-frontend/src/components/common/SearchBar.vue
  itta-bab-frontend/src/components/group/SearchBarAndSort.vue
  itta-bab-frontend/src/views/group/GroupList.vue
Labels: feat, refactor

#61 feat: main 페이지 캘린더 추가
  itta-bab-frontend/package-lock.json
  itta-bab-frontend/package.json
  itta-bab-frontend/src/components/common/Calendar.vue
  itta-bab-frontend/src/main.js
  itta-bab-frontend/src/views/Home.vue
Labels: feat

#60 feat: store 메인화면 구현 및 naver map API key 추가 및 .env 파일 gitignore에 경로 설정
  itta-bab-frontend/.gitignore
  itta-bab-frontend/src/components/common/StoreMapApi.vue
  itta-bab-frontend/src/components/common/StoreSearchBarAndSort.vue
  itta-bab-frontend/src/components/store/StoreList.vue
  itta-bab-frontend/src/views/store/StoreDetail.vue
Labels: feat

#66 docs: 스타일 이슈 템플릿 삭제
  .github/ISSUE_TEMPLATE/스타일.md
Labels: docs

#65 feat: 메인 페이지 구현
  itta-bab-frontend/src/components/common/Calendar.vue
  itta-bab-frontend/src/components/user/GroupList.vue
  itta-bab-frontend/src/components/user/PostList.vue
  itta-bab-frontend/src/components/user/StoreList.vue
  itta-bab-frontend/src/main.js
  itta-bab-frontend/src/views/Home.vue
Labels: feat

#63 refactor: list 디자인 수정
  itta-bab-frontend/src/components/common/List.vue
  itta-bab-frontend/src/components/common/PageNumAndWritingButton.vue
  itta-bab-frontend/src/views/board/PostDetail.vue
  itta-bab-frontend/src/views/inquiry/InquiryList.vue
Labels: refactor

#68 feat: PostComment 페이지 구현
  itta-bab-frontend/src/main.js
  itta-bab-frontend/src/router/board.js
  itta-bab-frontend/src/router/index.js
  itta-bab-frontend/src/views/board/PostComment.vue
Labels: feat

#77 feat: 회원 정보 수정, 회원 탈퇴
  itta-bab-frontend/src/components/user/DeleteUser.vue
  itta-bab-frontend/src/components/user/UserDetailAndChatList.vue
  itta-bab-frontend/src/router/user.js
  itta-bab-frontend/src/views/user/DeleteUser.vue
  itta-bab-frontend/src/views/user/UpdateUserInfo.vue
Labels: feat

#78 feat: 로그인 api 구현
  itta-bab-frontend/package-lock.json
  itta-bab-frontend/package.json
  itta-bab-frontend/src/components/common/Header.vue
  itta-bab-frontend/src/components/user/LoginForm.vue
  itta-bab-frontend/src/main.js
  itta-bab-frontend/src/router/index.js
  itta-bab-frontend/src/stores/auth.js
Labels: feat

#79 feat: 관리자 모임 카테고리 UI 개발
  itta-bab-frontend/src/components/common/AdminTopSection.vue
  itta-bab-frontend/src/components/common/DeleteButton.vue
  itta-bab-frontend/src/components/common/SearchBar.vue
  itta-bab-frontend/src/router/group.js
  itta-bab-frontend/src/views/group/GroupCategoryList.vue
Labels: feat

#81 feat: 화면 비율 수정
  itta-bab-frontend/src/components/common/List.vue
  itta-bab-frontend/src/components/common/PageNumAndWritingButton.vue
  itta-bab-frontend/src/components/common/SearchBarAndSort.vue
  itta-bab-frontend/src/views/board/PostComment.vue
  itta-bab-frontend/src/views/inquiry/InquiryList.vue
  itta-bab-frontend/src/views/report/ReportList.vue
Labels: feat

#86 feat: 가게 상세 정보 미완성.. 민주님에게 토스
  itta-bab-frontend/src/assets/css/resetcss.css
  itta-bab-frontend/src/components/common/List.vue
  itta-bab-frontend/src/components/store/MenuList.vue
  itta-bab-frontend/src/components/store/StoreList.vue
  itta-bab-frontend/src/views/store/MenuMain.vue
  itta-bab-frontend/src/views/store/StoreDetail.vue
  itta-bab-frontend/src/views/store/StoreMain.vue
Labels: feat

#85 feat: 회원 탈퇴 완료 구현
  itta-bab-frontend/src/router/user.js
  itta-bab-frontend/src/views/user/DeleteUser.vue
  itta-bab-frontend/src/views/user/DeleteUserResult.vue
Labels: feat

#87 chore: lodash.template 패키지 삭제
  itta-bab-frontend/package-lock.json
Labels: chore

#88 feat: 게시판 검색 기능 추가
  itta-bab-frontend/src/components/common/SearchBarAndSort.vue
  itta-bab-frontend/src/views/board/PostDetail.vue
Labels: feat

#89 feat: 관리자 모임 카테고리 등록 화면 UI 개발
  itta-bab-frontend/src/components/common/AdminTopSection.vue
  itta-bab-frontend/src/components/common/BottomPageButton.vue
  itta-bab-frontend/src/views/group/GroupCategoryList.vue
  itta-bab-frontend/src/views/group/GroupCategoryRegister.vue
  itta-bab-frontend/src/views/group/GroupList.vue
Labels: feat

#93 feat: 알림 컴포넌트 구현
  itta-bab-frontend/src/assets/icons/alarm-group-gray.svg
  itta-bab-frontend/src/assets/icons/alarm-post-gray.svg
  itta-bab-frontend/src/assets/icons/alarm-review-gray.svg
  itta-bab-frontend/src/components/common/Header.vue
  itta-bab-frontend/src/components/common/Notification.vue
Labels: feat

#94 feat: 관리자 메뉴 카테고리 등록, 수정 UI 개발
  itta-bab-frontend/src/views/group/GroupCategoryList.vue
  itta-bab-frontend/src/views/group/GroupList.vue
  itta-bab-frontend/src/views/store/MenuCategoryModify.vue
  itta-bab-frontend/src/views/store/MenuCategoryRegister.vue
Labels: fix, feat

#92 feat: 관리자 부트캠프 기능 구현
  itta-bab-frontend/src/components/admin/BootcampForm.vue
  itta-bab-frontend/src/components/admin/CoruseList.vue
  itta-bab-frontend/src/components/admin/Createcourse.vue
  itta-bab-frontend/src/components/admin/Updatebootcamp.vue
  itta-bab-frontend/src/components/admin/Updatecourse.vue
  itta-bab-frontend/src/router/admin.js
  itta-bab-frontend/src/router/index.js
Labels: feat

#97 feat: 관리자 메뉴 카테고리 목록 UI 구현
  itta-bab-frontend/src/main.js
  itta-bab-frontend/src/router/board.js
  itta-bab-frontend/src/views/store/MenuCategoryList.vue
Labels: feat

#98 feat: store detail 구현 및 수정
  itta-bab-frontend/src/components/common/Page.vue
  itta-bab-frontend/src/components/store/MenuList.vue
  itta-bab-frontend/src/main.js
  itta-bab-frontend/src/views/store/StoreDetail.vue
Labels: fix, feat

#99 feat: 더보기 버튼 추가
  itta-bab-frontend/src/components/common/Notification.vue
  itta-bab-frontend/src/main.js
Labels: feat

#101 feat: 관리자 가게 목록 UI 개발
  itta-bab-frontend/src/router/board.js
  itta-bab-frontend/src/views/store/StoreList.vue
Labels: feat

#104 fix: 헤더 수정
  itta-bab-frontend/src/components/common/Header.vue
  itta-bab-frontend/src/components/common/Notification.vue
Labels: fix

#103 feat: store 검색기능 추가
  itta-bab-frontend/src/components/common/StoreSearchBarAndSort.vue
  itta-bab-frontend/src/views/store/StoreMain.vue
Labels: feat

#107 feat: inquiry 관리자 답변 페이지 구현
  itta-bab-frontend/src/router/inquiry.js
  itta-bab-frontend/src/views/inquiry/InquiryAdminResponse.vue
Labels: feat

#108 feat: 관리자 가게 상세 UI 개발
  itta-bab-frontend/src/components/store/MenuList.vue
  itta-bab-frontend/src/router/store.js
  itta-bab-frontend/src/views/store/AdminStoreDetail.vue
Labels: feat

#111 feat: adminTap 부분 링크 수정 추가
  itta-bab-frontend/src/components/admin/AdminTap.vue
Labels: feat

#114 feat: 가게 리뷰 추가 및 페이징바 UI 개선
  itta-bab-frontend/src/components/store/ReviewList.vue
  itta-bab-frontend/src/router/store.js
  itta-bab-frontend/src/views/store/ReviewMain.vue
  itta-bab-frontend/src/views/store/StoreMain.vue
Labels: feat

#113 feat: 마이페이지 api 연동
  itta-bab-frontend/src/components/user/UserDetailAndChatList.vue
Labels: feat

#116 feat: schedule db 연동
  itta-bab-frontend/src/App.vue
  itta-bab-frontend/src/components/common/Calendar.vue
Labels: feat

#117 feat: 권한 체크 추가
  itta-bab-frontend/src/components/user/UserDetailAndChatList.vue
  itta-bab-frontend/src/stores/auth.js
Labels: feat

#120 feat: 모임 API, 모임 카테고리 API 연동
  itta-bab-frontend/src/views/group/GroupList.vue
Labels: feat

#122 feat: 익명커뮤니티 API연동
  itta-bab-frontend/src/views/board/PostDetail.vue
Labels: feat

#128 feat: 모임 등록 API 연동
  itta-bab-frontend/src/router/group.js
  itta-bab-frontend/src/views/group/GroupList.vue
  itta-bab-frontend/src/views/group/GroupRegister.vue
Labels: feat

#130 feat: 모임 목록 신고 기능 개발
  itta-bab-frontend/src/components/common/ReportButton.vue
  itta-bab-frontend/src/views/group/GroupList.vue
  itta-bab-frontend/src/views/group/GroupRegister.vue
  itta-bab-frontend/src/views/user/DeleteUser.vue
Labels: feat, refactor

#132 feat: 가게 조회 및 등록 API 연결
  itta-bab-frontend/src/components/store/StoreForm.vue
  itta-bab-frontend/src/views/store/ReviewMain.vue
  itta-bab-frontend/src/views/store/StoreCreate.vue
  itta-bab-frontend/src/views/store/StoreMain.vue
Labels: feat

#134 feat: 게시글 작성 api 연결
  itta-bab-frontend/src/views/board/PostCreate.vue
Labels: feat

#127 feat: 사용자 문의 등록 DB 연결
  itta-bab-frontend/src/components/user/UserDetailAndChatList.vue
  itta-bab-frontend/src/views/inquiry/Inquiry.vue
Labels: feat

#136 feat: 문의 답변 구현
  itta-bab-frontend/src/components/user/LoginForm.vue
  itta-bab-frontend/src/router/admin.js
  itta-bab-frontend/src/router/index.js
  itta-bab-frontend/src/router/inquiry.js
  itta-bab-frontend/src/stores/auth.js
  itta-bab-frontend/src/views/AdminTap.vue
  itta-bab-frontend/src/views/inquiry/InquiryAdminResponse.vue
  itta-bab-frontend/src/views/inquiry/InquiryList.vue
Labels: feat

#138 feat: 문의 기능 구현
  itta-bab-frontend/src/views/inquiry/Inquiry.vue
Labels: feat

#142 feat: 문의 완료
  itta-bab-frontend/src/router/inquiry.js
  itta-bab-frontend/src/views/inquiry/InquiryAdminResponse.vue
  itta-bab-frontend/src/views/inquiry/InquiryList.vue
Labels: feat

#143 feat: 메뉴 API 추가 및 라우팅 설정
  itta-bab-frontend/src/components/store/CreateMenuForm.vue
  itta-bab-frontend/src/components/store/MenuList.vue
  itta-bab-frontend/src/router/store.js
  itta-bab-frontend/src/views/store/MenuCreate.vue
  itta-bab-frontend/src/views/store/MenuMain.vue
  itta-bab-frontend/src/views/store/StoreMain.vue
  itta-bab-frontend/src/views/store/StoreUpdate.vue
Labels: feat

#145 feat: mypage 참여중인 모임 API 연동
  itta-bab-frontend/src/components/common/ReportButton.vue
  itta-bab-frontend/src/components/user/UserDetailAndChatList.vue
  itta-bab-frontend/src/views/group/GroupDetail.vue
  itta-bab-frontend/src/views/group/GroupList.vue
  itta-bab-frontend/src/views/user/MyPage.vue
Labels: feat

#148 feat:익명게시판 신고 기능 추가
  itta-bab-frontend/src/router/board.js
  itta-bab-frontend/src/views/board/PostDetail.vue
Labels: feat

#150 feat: 신고 기능
  itta-bab-frontend/src/router/report.js
  itta-bab-frontend/src/views/board/PostDetail.vue
  itta-bab-frontend/src/views/group/GroupList.vue
  itta-bab-frontend/src/views/report/ReportCreate.vue
Labels: feat

#152 feat: 아이디 찾기, 비밀번호 찾기 api 연동
  itta-bab-frontend/src/components/common/Header.vue
  itta-bab-frontend/src/components/user/FindIdForm.vue
  itta-bab-frontend/src/components/user/FindIdResultDetail.vue
  itta-bab-frontend/src/components/user/FindPasswordForm.vue
  itta-bab-frontend/src/components/user/FindPwdResultDetail.vue
  itta-bab-frontend/src/router/user.js
  itta-bab-frontend/src/views/user/FindIdResult.vue
  itta-bab-frontend/src/views/user/FindPwdResult.vue
  itta-bab-frontend/src/views/user/SignUp.vue
Labels: feat

#153 refactor: 좋아요, 신고 버튼 추가
  itta-bab-frontend/src/components/user/UserDetailAndChatList.vue
  itta-bab-frontend/src/views/group/GroupChat.vue
  itta-bab-frontend/src/views/group/GroupDetail.vue
  itta-bab-frontend/src/views/group/GroupList.vue
Labels: feat, refactor

#158 feat: 일정 crud 완료
  itta-bab-frontend/src/components/common/Calendar.vue
  itta-bab-frontend/src/router/schedule.js
Labels: feat

#162 feat: 게시판 댓글 기능 구현
  itta-bab-frontend/src/views/board/PostComment.vue
  itta-bab-frontend/src/views/board/PostDetail.vue
Labels: feat

#155 feat: 가게, 메뉴 수정 구현 및 UI 개선
  itta-bab-frontend/src/router/store.js
  itta-bab-frontend/src/views/store/MenuCreate.vue
  itta-bab-frontend/src/views/store/MenuMain.vue
  itta-bab-frontend/src/views/store/MenuUpdate.vue
  itta-bab-frontend/src/views/store/StoreMain.vue
  itta-bab-frontend/src/views/store/StoreUpdate.vue
Labels: feat

#161 feat: 관리자 모임 카테고리 API 연동
  itta-bab-frontend/src/components/common/DeleteButton.vue
  itta-bab-frontend/src/components/user/UserDetailAndChatList.vue
  itta-bab-frontend/src/router/group.js
  itta-bab-frontend/src/views/group/GroupCategoryList.vue
  itta-bab-frontend/src/views/group/GroupCategoryRegister.vue
  itta-bab-frontend/src/views/group/GroupChat.vue
Labels: feat

#163 feat: 마이페이지 api 연동
  itta-bab-frontend/src/assets/css/resetcss.css
  itta-bab-frontend/src/assets/icons/star.svg
  itta-bab-frontend/src/components/common/Header.vue
  itta-bab-frontend/src/components/user/BookmarksList.vue
  itta-bab-frontend/src/components/user/CommentsList.vue
  itta-bab-frontend/src/components/user/FriendsList.vue
  itta-bab-frontend/src/components/user/InquiryList.vue
  itta-bab-frontend/src/components/user/NotificationsList.vue
  itta-bab-frontend/src/components/user/ReportsList.vue
  itta-bab-frontend/src/components/user/ReviewsList.vue
  itta-bab-frontend/src/components/user/UserTap.vue
  itta-bab-frontend/src/components/user/WrittenPostsList.vue
  itta-bab-frontend/src/views/inquiry/InquiryList.vue
  itta-bab-frontend/src/views/user/MyPage.vue
Labels: feat

#164 feat: 가게 상세 페이지 구현(가게, 메뉴)
  itta-bab-frontend/src/router/store.js
  itta-bab-frontend/src/views/store/MenuCreate.vue
  itta-bab-frontend/src/views/store/MenuMain.vue
  itta-bab-frontend/src/views/store/MenuUpdate.vue
  itta-bab-frontend/src/views/store/StoreDetail.vue
  itta-bab-frontend/src/views/store/StoreMain.vue
Labels: feat

#168 feat: admin, post 관련 수정 및 구현
  itta-bab-frontend/src/components/admin/InquiryAdminResponse.vue
  itta-bab-frontend/src/components/admin/InquiryList.vue
  itta-bab-frontend/src/components/admin/ReportList.vue
  itta-bab-frontend/src/router/inquiry.js
  itta-bab-frontend/src/router/report.js
  itta-bab-frontend/src/views/AdminTap.vue
  itta-bab-frontend/src/views/group/GroupDetail.vue
  itta-bab-frontend/src/views/report/ReportCreate.vue
  itta-bab-frontend/src/views/report/ReportList.vue
Labels: feat, refactor

#173 feat: store UI 개선 및 예외처리 추가, 리뷰 조회 페이지 구현
  itta-bab-frontend/src/views/store/ReviewMain.vue
  itta-bab-frontend/src/views/store/StoreDetail.vue
  itta-bab-frontend/src/views/store/StoreMain.vue
Labels: feat

#169 feat: 댓글 등록 기능 활성화 버튼 클릭시 등록
  itta-bab-frontend/src/views/board/PostComment.vue
Labels: feat

#171 feat: 관리자 신고 처리
  itta-bab-frontend/src/components/admin/ReportList.vue
  itta-bab-frontend/src/views/AdminTap.vue
Labels: feat, refactor

#174 feat: group/#172
  itta-bab-frontend/src/components/user/GroupList.vue
Labels: feat

#175 feat: 리뷰 상세 조회 페이지 구현 및 UI
  itta-bab-frontend/src/router/store.js
  itta-bab-frontend/src/views/store/ReviewMain.vue
  itta-bab-frontend/src/views/store/StoreDetail.vue
Labels: feat

#176 feat: 게시글 불러오기 기능 추가 및 댓글 익명성 보장
  itta-bab-frontend/src/views/board/PostComment.vue
Labels: feat

#177 feat: 가게 즐겨찾기 등록 및 삭제 추가
  itta-bab-frontend/src/views/store/StoreDetail.vue
Labels: feat

#181 feat: groupDetail 페이지 구현
  itta-bab-frontend/src/views/board/PostDetail.vue
  itta-bab-frontend/src/views/group/GroupDetail.vue
Labels: feat

#184 feat: 모임 참가 버튼 추가 및 멘트 수정
  itta-bab-frontend/src/views/group/GroupDetail.vue
Labels: feat

#185 feat: 게시판 좋아요 API 연동
  itta-bab-frontend/src/views/board/PostComment.vue
  itta-bab-frontend/src/views/group/GroupChat.vue
Labels: feat

#186 feat: 친구 관련 api 연동
  images/friend/friendaccept.gif
  images/friend/friendadd.gif
  images/friend/frienddelete.gif
  images/friend/friendreject.gif
  itta-bab-frontend/src/assets/icons/friend-plus.svg
  itta-bab-frontend/src/components/common/Friend.vue
  itta-bab-frontend/src/components/user/FriendsList.vue
  itta-bab-frontend/src/views/user/DeleteUser.vue
Labels: feat

#187 feat: 리뷰 기능 추가, 라우팅 추가, 가게 검색 및 정렬 추가
  itta-bab-frontend/src/components/common/StoreSearchBarAndSort.vue
  itta-bab-frontend/src/router/store.js
  itta-bab-frontend/src/views/store/MenuMain.vue
  itta-bab-frontend/src/views/store/MenuUpdate.vue
  itta-bab-frontend/src/views/store/ReviewCreate.vue
  itta-bab-frontend/src/views/store/ReviewMain.vue
  itta-bab-frontend/src/views/store/StoreCreate.vue
  itta-bab-frontend/src/views/store/StoreDetail.vue
  itta-bab-frontend/src/views/store/StoreMain.vue
  itta-bab-frontend/src/views/store/StoreUpdate.vue
Labels: feat

#188 fix : 가게 등록 후 라우팅 수정
  itta-bab-frontend/src/router/store.js
  itta-bab-frontend/src/views/store/StoreCreate.vue
Labels: feat

#190 docs: 리드미 수정
  README.md
Labels: docs
